[package]
name = "messagebus-demo"
authors = ["Andrey Tkachenko <andrey@aidev.ru>"]
repository = "https://github.com/andreytkachenko/messagebus-demo.git"
version = "0.1.0"
edition = "2021"

[dependencies]
messagebus = "0.9.7"
messagebus_derive = "0.2.3"
